name: Build and Deploy

on:
    push:
        branches: [ "main" , "dev"]

env:
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  SERVICE_NAME: ${{ vars.SERVICE_NAME }}
      
permissions:
  contents: read
  id-token: write

jobs:
  build-push:
    environment: ${{ github.ref_name == 'dev' && 'dev' || github.ref_name == 'main' && 'prd' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v3
        with:
          project_id: poc-suroeste
          workload_identity_provider: projects/294493969622/locations/global/workloadIdentityPools/github/providers/github-minddash
          service_account: github-action-deployer@poc-suroeste.iam.gserviceaccount.com

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'
      
      - run: |
          gcloud builds submit . \
            --tag us-docker.pkg.dev/poc-suroeste/minddash/$IMAGE_NAME:latest \
            --gcs-source-staging-dir="gs://poc-suroeste_cloudbuild/source" \
            --gcs-log-dir="gs://poc-suroeste_cloudbuild/logs"

  deploy:
    needs: build-push
    environment: ${{ github.ref_name == 'dev' && 'dev' || github.ref_name == 'main' && 'prd' }}
    runs-on: ubuntu-latest
    steps:
      - id: auth
        uses: google-github-actions/auth@v3
        with:
          project_id: poc-suroeste
          workload_identity_provider: projects/294493969622/locations/global/workloadIdentityPools/github/providers/github-minddash
          service_account: github-action-deployer@poc-suroeste.iam.gserviceaccount.com
      
      - name: Update Cloud Run Service
        run: |
          gcloud run services update \
          $SERVICE_NAME \
          --platform=managed \
          --image=us-docker.pkg.dev/poc-suroeste/minddash/$IMAGE_NAME:latest \
          --region=us-central1 \
          --quiet